version: 2.1
orbs:
  solidusio_extensions: solidusio/extensions@0.2.24

jobs:
  run-specs-with-postgres:
    executor: solidusio_extensions/postgres
    steps:
      - checkout
      - solidusio_extensions/run-tests-solidus-older
      - solidusio_extensions/store-test-results

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - run-specs-with-postgres
